/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BoostButton {
        "sendPaymentFunc": Function;
    }
    interface VideoOverlay {
        "setVideoElement": (el: any) => Promise<void>;
    }
}
declare global {
    interface HTMLBoostButtonElement extends Components.BoostButton, HTMLStencilElement {
    }
    var HTMLBoostButtonElement: {
        prototype: HTMLBoostButtonElement;
        new (): HTMLBoostButtonElement;
    };
    interface HTMLVideoOverlayElement extends Components.VideoOverlay, HTMLStencilElement {
    }
    var HTMLVideoOverlayElement: {
        prototype: HTMLVideoOverlayElement;
        new (): HTMLVideoOverlayElement;
    };
    interface HTMLElementTagNameMap {
        "boost-button": HTMLBoostButtonElement;
        "video-overlay": HTMLVideoOverlayElement;
    }
}
declare namespace LocalJSX {
    interface BoostButton {
        "sendPaymentFunc": Function;
    }
    interface VideoOverlay {
    }
    interface IntrinsicElements {
        "boost-button": BoostButton;
        "video-overlay": VideoOverlay;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "boost-button": LocalJSX.BoostButton & JSXBase.HTMLAttributes<HTMLBoostButtonElement>;
            "video-overlay": LocalJSX.VideoOverlay & JSXBase.HTMLAttributes<HTMLVideoOverlayElement>;
        }
    }
}
