/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BoostButton {
    }
}
declare global {
    interface HTMLBoostButtonElement extends Components.BoostButton, HTMLStencilElement {
    }
    var HTMLBoostButtonElement: {
        prototype: HTMLBoostButtonElement;
        new (): HTMLBoostButtonElement;
    };
    interface HTMLElementTagNameMap {
        "boost-button": HTMLBoostButtonElement;
    }
}
declare namespace LocalJSX {
    interface BoostButton {
    }
    interface IntrinsicElements {
        "boost-button": BoostButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "boost-button": LocalJSX.BoostButton & JSXBase.HTMLAttributes<HTMLBoostButtonElement>;
        }
    }
}
